pipeline {
    agent none  // No execution on the master node

    environment {
        DOCKER_IMAGE = 'sandeepkalathil/html-website'
        CONTAINER_NAME = 'html-web-container'  // Name for the new container
        EXPOSED_PORT = '8020'  // Port to expose on the host
    }

    stages {
       

        stage('Build Docker Image') {
            agent { label 'Docker-Agent' }
            steps {
                script {
                    echo '🔹 Building Docker image...'
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Push to Docker Hub') {
            agent { label 'Docker-Agent' }
            steps {
                script {
                    echo '🔹 Logging into Docker Hub...'
                    sh 'docker login -u yourdockerhubusername -p yourpassword'
                    echo '🔹 Pushing image to Docker Hub...'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy New Container') {
            agent { label 'Docker-Agent' }
            steps {
                script {
                    echo '🔹 Stopping any existing container...'
                    sh "docker stop $CONTAINER_NAME || true"
                    sh "docker rm $CONTAINER_NAME || true"

                    echo '🔹 Running a new container...'
                    sh """
                    docker run -d --name $CONTAINER_NAME -p $EXPOSED_PORT:8020 $DOCKER_IMAGE
                    """
                }
            }
        }
    }
}
