pipeline {
    agent none  // No execution on the master node

    environment {
        DOCKER_IMAGE = 'sandeepkalathil/html-website'
        CONTAINER_NAME = 'html-web-container'  // Name for the new container
        EXPOSED_PORT = '8020'  // Port to expose on the host
    }

    stages {
        
        stage('Deploy New Container') {
            agent { label 'Docker-Agent' }
            steps {
                script {
                    echo '🔹 Pulling latest image from Docker Hub...'
                    sh "docker pull $DOCKER_IMAGE"

                    echo '🔹 Stopping any existing container...'
                    sh "docker stop $CONTAINER_NAME || true"
                    sh "docker rm $CONTAINER_NAME || true"

                    echo '🔹 Running a new container...'
                    sh """
                    docker run -d --name $CONTAINER_NAME -p $EXPOSED_PORT:80 $DOCKER_IMAGE
                    """
                }
            }
        }
    }
}
