pipeline {
    agent { label 'Docker-Agent' } 

    stages {
        stage('Back-end') {
            agent {
                docker { 
                    image 'maven:3.8.7-openjdk-18'
                    args '--rm' // Removes container after execution
                }
            }
            steps {
                script {
                    echo '🔹 Running Maven inside Docker...'
                    sh 'mvn --version'
                }
            }
        }

        stage('Front-end') {
            agent {
                docker { 
                    image 'node:16-alpine' 
                    args '--rm'
                }
            }
            steps {
                script {
                    echo '🔹 Running Node.js inside Docker...'
                    sh 'node --version'
                }
            }
        }
    }
}
