pipeline {
  agent { label 'Docker-Agent' } 
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.7-openjdk-18' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}